import "./globals.css";
import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";

const poppins = Poppins({
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "800",
    "900",
    "400",
    "700",
  ],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html className={poppins.className} lang="en">
      <body>{children}</body>
    </html>
  );
}
